#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUT_DIR="$ROOT_DIR/frontend/src/lib/contract"
NETWORK="testnet"
CONTRACT_ID=""

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/sync-abi.sh --contract-id <CONTRACT_ID> [--network testnet]

Description:
  Uses `stellar contract inspect` to fetch Soroban contract metadata and
  generates frontend ABI artifacts:
    - frontend/src/lib/contract/abi.json
    - frontend/src/lib/contract/abi.ts
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --contract-id)
      [ "$#" -ge 2 ] || { echo "error: --contract-id requires a value" >&2; exit 1; }
      CONTRACT_ID="$2"
      shift 2
      ;;
    --network)
      [ "$#" -ge 2 ] || { echo "error: --network requires a value" >&2; exit 1; }
      NETWORK="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

[ -n "$CONTRACT_ID" ] || { echo "error: --contract-id is required" >&2; usage; exit 1; }
command -v stellar >/dev/null 2>&1 || { echo "error: stellar CLI not found in PATH" >&2; exit 1; }

mkdir -p "$OUT_DIR"
ABI_JSON="$OUT_DIR/abi.json"
ABI_TS="$OUT_DIR/abi.ts"

echo "Inspecting contract '$CONTRACT_ID' on '$NETWORK'..."
stellar contract inspect --id "$CONTRACT_ID" --network "$NETWORK" --output json > "$ABI_JSON"

{
  printf '/* Auto-generated by scripts/sync-abi.sh. Do not edit manually. */\n'
  printf 'export const contractAbi = '
  cat "$ABI_JSON"
  printf ' as const;\n'
  printf 'export type ContractAbi = typeof contractAbi;\n'
} > "$ABI_TS"

echo "ABI synced:"
echo "  - $ABI_JSON"
echo "  - $ABI_TS"
