name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1 # v4.2.2

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup-node

      - name: ESLint
        working-directory: frontend
        run: npm run lint

      - name: Prettier check
        working-directory: frontend
        run: npx prettier --check .
