name: Contract Checks

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@89b12181fb390509a0842a86cc55eeb8eb928c1d # stable
        with:
          components: clippy, rustfmt
          targets: wasm32v1-none

      - name: Cache cargo
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: contracts/stellar-give

      - name: Format check
        working-directory: contracts/stellar-give
        run: cargo fmt --check

      - name: Clippy
        working-directory: contracts/stellar-give
        run: cargo clippy -- -D warnings

      - name: Test
        working-directory: contracts/stellar-give
        run: cargo test --locked
